---
title: "Module 5 Project Report"
author: "stop_drop_and_code"
date: "2022-10-10"
output: html_document
---
```{r, include=FALSE}
library(tidyverse)
library(knitr)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Introduction


#Methods

#Results

```{r cars}
library(tidyverse)
dat.f <- list.files(pattern = "couch|active.csv") #find the files

dat.l <- list() #make an empty list

for(i in dat.f){
  met.dat<- unlist(strsplit(i,"_")) #split of the filename string
  who <- met.dat[1] #store the first element
  activity <- gsub(".csv","",met.dat[2]) #store second element, dropping CSV with gsub()
  dat.l[[i]]<- read_csv(i)%>%
    mutate(who=who,activity=activity)#read, then store data with additional columns of metada in list as position unique to i
}
dat <- do.call(rbind,dat.l) #combine the list into table

dat%>%
  ggplot()+geom_boxplot(aes(x=activity,y=degC))+facet_grid(.~who) #plot to see what we get
```

```{r pressure, echo=FALSE}
plot(pressure)
```

#Author Contributions

Rachel R: Arduino setup and code

Rachel Z:

Jordan:

Michael: Data collection and production of .csv files, Results section, 

#References
